---
- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - block:
        - name: initial block debug
          debug: msg='any_errors_fatal,  i execute normally'

        - name: any_errors_fatal, initial block, bin/fasel to simulate failure
          command: /bin/false

        - debug: msg='any errors fatal, i never execute, cause ERROR!'
      #rescue:
      #  - name: any_errors_fatal rescure block debug
      #    debug: msg='any_errors_fatal, rescue block... I caught an error'

      #  - name: any_errors_fatal in rescue block, using bin/flase to simulate error
      #    command: /bin/false

      #  - name: any_errors_fatal post debug
      #   debug: msg='any_errors_fatal, I also never execute :-('
      always:
        - name: any_errors_fatal always block debug
          debug: msg="any errors fatal, always block.. this always executes"

          #        - set_fact:
          #   always_ran: true
              #    - name: any_errors_fatal fact debug
              #      debug:
              #        var: always_ran



