---
- hosts: localhost
  environment:
    foo: bar
  handlers:
    - name: handler env
      debug: var=environment
      register: environment
  tasks:
    - name: task print env
      changed_when: true
      notify: handler env
      debug: var=environment
