---
- hosts: localhost
  #  strategy: debug
  gather_facts: no
  tasks:
    - name: Execute test role
      include_role:
        name: "testrole_{{item}}"
      with_items:
        - 'one'
        - 'two'
        - 'three'
      ignore_errors: true

    - name: Execute test role static no
      static: no
      include_role:
        name: "testrole_{{item}}"
      with_items:
        - 'one'
        - 'two'
        - 'three'
      ignore_errors: true

    - name: Execute test role static no allow_duplicates yes
      static: no
      include_role:
        name: "testrole_{{item}}"
        allow_duplicates: true
      with_items:
        - 'one'
        - 'two'
        - 'three'
      ignore_errors: true
