---
- hosts: vagrant-ubuntu
  become: yes
  become_user: root
  tasks:
    - name: delete existing
      file: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list state=absent

    - name: 'mode specified as yaml literal 0600'
      apt_repository:
        repo: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
        state: present
        mode: 0600
      register: mode_given_results

    - name: gather mode_given_as_literal_yaml stat
      stat: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list
      register: mode_given_yaml_literal_0600

    - name: show mode_given_yaml_literal_0600
      debug: var=mode_given_yaml_literal_0600

    - name: delete existing
      file: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list state=absent

    - name: 'no mode specified'
      apt_repository:
         repo: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
         state: present
      register: no_mode_results

    - name: gather no mode stat
      stat: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list
      register: no_mode_stat

    - name: show no mode stat
      debug: var=no_mode_stat

    - name: delete
      file: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list state=absent

    - name: delete again
      file: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list state=absent

    - name: 'mode specified as yaml literal 600'
      apt_repository:
        repo: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
        state: present
        mode: 600
      register: mode_given_short_results

    - name: gather mode_given_yaml_literal_600 stat
      stat: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list
      register: mode_given_yaml_literal_600

    - name: show mode_given_yaml_literal_600
      debug: var=mode_given_yaml_literal_600

    - name: delete again
      file: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list state=absent

    - name: 'mode specified as string 0600'
      apt_repository:
         repo: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
         state: present
         mode: "0600"
      register: mode_given_string_results

    - name: gather mode_given_string stat
      stat: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list
      register: mode_given_string_stat

    - name: show mode_given_string_stat
      debug: var=mode_given_string_stat


    - name: delete again
      file: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list state=absent

    - name: 'mode specified as string 600'
      apt_repository:
         repo: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
         state: present
         mode: "600"
      register: mode_given_string_600_results

    - name: gather mode_given_600_string stat
      stat: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list
      register: mode_given_string_600_stat

    - name: show mode_given_string_stat
      debug: var=mode_given_string_600_stat

    - name: delete again
      file: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list state=absent

    # Asserts
    - name: assert mode_given_stat_as_literal_yaml is correct
      assert: { that: "mode_given_stat_as_literal_yaml.stat.mode == '0600'" }

    - name: assert no_mode_stat is correct
      assert: { that: "no_mode_stat.stat.mode == '0644'" }

    - name: assert mode_given_string_stat is correct
      assert: { that: "mode_given_string_stat.stat.mode == '0600'" }

    - name: assert mode is correct
      assert: { that: "mode_given_string_600_stat.stat.mode == '0600'" }

    # Will fail
    - name: assert mode_given_yaml_literal_600 is correct
      assert: { that: "mode_given_yaml_literal_600.stat.mode == '0600'" }

    - name: 'mode specified as bogus float'
      apt_repository:
         repo: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
         state: present
         mode: 9.9999999
      register: mode_float_results


    - name: gather mode_floar stat
      stat: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list
      register: mode_float_stat

    - name: show mode_float_stat
      debug: var=mode_float_stat

    - name: delete again for float
      file: path=/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list state=absent


#    - name: 'hey with mode specified'
#      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present mode=0644

#    - name: 'hey with mode specified as quoted string'
#      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present mode="0644"

#    - name: 'hey with mode specified as float'
#      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present mode=1.2345

    - name: 'hey with mode specified as huge int'
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present mode=99999999999999999999999999999999999999999999999999999999999999
