---

- name: Demonstrate memory growth as tasks are included
  hosts: localhost
  gather_facts: false
  vars:
    include_count: 10
  tasks:
    - include: foo/some_tasks.yml
      with_sequence: start=1 end="{{ include_count|int}}"

    - include: foo/some_tasks.yml
      with_sequence: start=1 end="{{ include_count|int}}"

    - include: foo/some_tasks.yml
      with_sequence: start=1 end="{{ include_count|int}}"
