- hosts: localhost
  gather_facts: no
  vars:
        # defaults (for single nodes)
        param1: "defaultParam1"
        param2: ~
        param3: ""
        param4: []

        # overrides (for multiple nodes)
        nodes:
          node1:
            config_path: /tmp/node1.conf
            config_overrides:
              param1: "node1Param1"
              param2: ~
              param3: ""
              param4: []
          node2:
            config_path: /tmp/node2.conf
            config_overrides:

        # dictionaries to be converted to json in config
        single_node_config:
          Param1: "{{ param1 }}"
          Param2: "{{ param2 }}"
          Param3: "{{ param3 }}"
          Param4: "{{ param4 }}"

        multi_node_config:
          Param1: "{{ item.value.config_overrides.param1 | default(param1) }}"
          Param2: "{{ item.value.config_overrides.param2 | default(param2) }}"
          Param3: "{{ item.value.config_overrides.param3 | default(param3) }}"
          Param4: "{{ item.value.config_overrides.param4 | default(param4) }}"

        # toggle
        enable_multi_nodes: false
  tasks:
        # task for single node
        - name: create config
          copy:
            content: "{{ single_node_config | to_nice_json }}"
            dest: /tmp/single.conf
          when: enable_multi_nodes != true

        # task multi nodes
        - name: create configs
          copy:
            content: "{{ multi_node_config | to_nice_json }}"
            dest: "{{ item.value.config_path }}"
          with_dict: "{{ nodes }}"
          when: enable_multi_nodes == true

