- hosts: localhost
  gather_facts: no
  vars:
        param2: ~

        foo:
          bar: ~
          baz: "{{ param2 }}"
  tasks:
        - debug: msg="{{ param2 }}"
        - debug: msg="{{ foo }}"
        - name: debug foo.bar should be None
          debug: msg="{{ foo.bar }}"
        - name: debug foo.baz should be None
          debug: msg="{{ foo.baz }}"

