- hosts: localhost
  gather_facts: no
  vars:
        param2: ~

        foo:
          bar: ~
          baz: "{{ param2 }}"
  tasks:
        - assert:
            that:
                - param2 == none
                - param2 is none
                - param2 is defined
                - param2 != ""

        - debug: msg="{{ param2 }}"

        - name: debug param2 with a default
          debug: msg="{{ param2|default('blippy') }}"

        - name: debug param2 with a default(true)
          debug: msg="{{ param2|default('blippy', true) }}"

        - name: debug none(param2)
          debug: msg="{% if param2 is none %}test{% else %} {{ param }} {% endif %}"

        - name: debug param3 not defined
          debug: msg="{{ param3|default('the_param3_default') }}"

        - debug: msg="{{ foo }}"

# foo.bar should be null, but ends up as empty string
        - debug: msg="foo.bar should be |null| but is |{{ foo.bar }}|"

        - assert:
            that:
                - foo.bar == none
                - foo.bar is none
                - foo.bar is defined
                - foo.bar != ""

        - debug: msg="foo.baz should be |null| but is |{{ foo.baz }}|"

        - assert:
            that:
                - foo.baz == none
                - foo.baz is none
                - foo.baz is defined
                - foo.baz != ""

