---
- hosts: all
  gather_facts: False

  tasks:
      - name: debug all group
        debug:
            var: groups.all

      - name: debug groups
        debug:
            var: groups

      - name: assert that all group is not empty
        assert:
          that:
            - groups['all']

      - name: assert that group1 is not empty
        assert:
          that:
            - groups['group1']

      - name: assert that ungrouped is empty
        assert:
          that:
            - groups['ungrouped'] == []
