- hosts: test
  tasks:
  - name: set test fact
    set_fact:
      test_eins: /tmp/te'st
      test_zwei: /tmp/te'st/static_component

  - name: test shell quote of variable
    shell: |
        echo {{ test_zwei | quote }}
    args:
      executable: "/bin/bash"

  - name: test shell quote of concat string
    shell: |
        echo {{ test_eins + '/static_component' | quote }}
    args:
      executable: "/bin/bash"
