- name: Testing notify handler with include
  hosts: localhost
  gather_facts: false
  roles:
    - { role: test }
  tasks:
    - name: command 1
      command: echo
      notify: "restart test debug"
    - name: command 2
      command: echo
      notify: "restart test debug"
    - name: command 3
      command: echo
      notify: "restart test debug"
    - name: command 4
      command: echo
      notify: "restart test debug"
      # handlers:
      #    - name: restart test debug
      #      include: tasks/restart_test_debug.yml


