---
- name: Testing notify handler with include
  hosts: localhost
  #become: True
  gather_facts: false
  handlers:
    - name: the name of restart test debug
      #include: tasks/restart_test.yml
      #include: tasks/restart_test_debug.yml
      command: echo "foo"
      listen: "restart test debug"

    - name: second handler
      #command: echo "foo second handler"
      include: tasks/restart_test_debug.yml
      static: true
      listen: "second handler"
  tasks:
    - command: id
      notify: "restart test debug"
    - command: id
      notify: "restart test debug"
    - command: id
      notify: "restart test debug"
    - command: id
      notify: "restart test debug"
    - command: id
      notify: "second handler"
    - command: id
      notify: "second handler"


